# Generated by Django 3.2.6 on 2021-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src', models.URLField(max_length=600, unique=True)),
                ('url', models.URLField(default='', max_length=600)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
