# Generated by Django 3.2.6 on 2021-08-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_image_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categorie',
        ),
    ]
