# Generated by Django 3.2.6 on 2021-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_image_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='categorie',
            field=models.CharField(default='demo_image', max_length=200),
        ),
    ]
