# Generated by Django 3.2.6 on 2021-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_image_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.URLField(max_length=1600, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default='', max_length=1600),
        ),
    ]
