# Generated by Django 3.2.6 on 2021-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
